program strange_attractors
  use iso_fortran_env, only : real64
  implicit none

  integer, parameter :: dp = real64
  integer, parameter :: samples = 30000
  real(dp), allocatable :: orbit(:, :)

  allocate(orbit(3, samples))

  call trace_system(1, [1.0_dp, 1.0_dp, 1.0_dp], 0.005_dp, 3000, orbit)
  call write_svg('lorenz.svg', 'Lorenz attractor', orbit, 1, 3, '#d8ef72')

  call trace_system(2, [0.1_dp, 0.0_dp, 0.0_dp], 0.010_dp, 5000, orbit)
  call write_svg('rossler.svg', 'Rossler attractor', orbit, 1, 2, '#78dec1')

  call trace_system(3, [0.1_dp, 0.0_dp, 0.0_dp], 0.020_dp, 5000, orbit)
  call write_svg('thomas.svg', 'Thomas attractor', orbit, 1, 3, '#efa6cb')

  print '(a)', 'Wrote lorenz.svg, rossler.svg, and thomas.svg'

contains

  subroutine trace_system(system_id, initial_state, dt, burn_in, points)
    integer, intent(in) :: system_id, burn_in
    real(dp), intent(in) :: initial_state(3), dt
    real(dp), intent(out) :: points(:, :)
    real(dp) :: state(3)
    integer :: i

    state = initial_state

    do i = 1, burn_in
      call rk4_step(system_id, state, dt)
    end do

    do i = 1, size(points, 2)
      call rk4_step(system_id, state, dt)
      points(:, i) = state
    end do
  end subroutine trace_system

  subroutine rk4_step(system_id, state, dt)
    integer, intent(in) :: system_id
    real(dp), intent(inout) :: state(3)
    real(dp), intent(in) :: dt
    real(dp) :: k1(3), k2(3), k3(3), k4(3)

    call velocity(system_id, state,                 k1)
    call velocity(system_id, state + 0.5_dp*dt*k1, k2)
    call velocity(system_id, state + 0.5_dp*dt*k2, k3)
    call velocity(system_id, state + dt*k3,        k4)

    state = state + dt*(k1 + 2.0_dp*k2 + 2.0_dp*k3 + k4)/6.0_dp
  end subroutine rk4_step

  subroutine velocity(system_id, state, rate)
    integer, intent(in) :: system_id
    real(dp), intent(in) :: state(3)
    real(dp), intent(out) :: rate(3)
    real(dp) :: x, y, z

    x = state(1)
    y = state(2)
    z = state(3)

    select case (system_id)
    case (1) ! Lorenz: sigma = 10, rho = 28, beta = 8/3
      rate = [10.0_dp*(y - x), &
              x*(28.0_dp - z) - y, &
              x*y - (8.0_dp/3.0_dp)*z]
    case (2) ! Rossler: a = 0.2, b = 0.2, c = 5.7
      rate = [-y - z, &
              x + 0.2_dp*y, &
              0.2_dp + z*(x - 5.7_dp)]
    case (3) ! Thomas: b = 0.208186
      rate = [sin(y) - 0.208186_dp*x, &
              sin(z) - 0.208186_dp*y, &
              sin(x) - 0.208186_dp*z]
    case default
      error stop 'Unknown system id'
    end select
  end subroutine velocity

  subroutine write_svg(file_name, title, points, x_axis, y_axis, colour)
    character(len=*), intent(in) :: file_name, title, colour
    real(dp), intent(in) :: points(:, :)
    integer, intent(in) :: x_axis, y_axis
    real(dp), parameter :: width = 960.0_dp
    real(dp), parameter :: height = 720.0_dp
    real(dp), parameter :: margin = 46.0_dp
    real(dp) :: x_min, x_max, y_min, y_max, scale, x_shift, y_shift
    real(dp) :: px, py
    integer :: file_unit, i

    x_min = minval(points(x_axis, :))
    x_max = maxval(points(x_axis, :))
    y_min = minval(points(y_axis, :))
    y_max = maxval(points(y_axis, :))

    scale = min((width - 2.0_dp*margin)/(x_max - x_min), &
                (height - 2.0_dp*margin)/(y_max - y_min))
    x_shift = 0.5_dp*(width - scale*(x_max - x_min))
    y_shift = 0.5_dp*(height - scale*(y_max - y_min))

    open(newunit=file_unit, file=file_name, status='replace', action='write')
    write(file_unit, '(a)') &
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 720" role="img">'
    write(file_unit, '(a)') '  <title>'//trim(title)//' generated by Fortran</title>'
    write(file_unit, '(a)') '  <defs>'
    write(file_unit, '(a)') &
      '    <pattern id="grid" width="48" height="48" patternUnits="userSpaceOnUse">'
    write(file_unit, '(a)') &
      '      <path d="M 48 0 L 0 0 0 48" fill="none" stroke="#263229" stroke-width="1"/>'
    write(file_unit, '(a)') '    </pattern>'
    write(file_unit, '(a)', advance='no') '    <polyline id="orbit" points="'

    do i = 1, size(points, 2), 2
      px = x_shift + scale*(points(x_axis, i) - x_min)
      py = height - (y_shift + scale*(points(y_axis, i) - y_min))
      write(file_unit, '(f0.2,a,f0.2,1x)', advance='no') px, ',', py
      if (mod(i, 160) == 1) write(file_unit, '(a)') ''
    end do

    write(file_unit, '(a)') '"/>'
    write(file_unit, '(a)') '  </defs>'
    write(file_unit, '(a)') '  <rect width="960" height="720" rx="24" fill="#0c100d"/>'
    write(file_unit, '(a)') '  <rect width="960" height="720" rx="24" fill="url(#grid)"/>'
    write(file_unit, '(a)') &
      '  <use href="#orbit" fill="none" stroke="'//trim(colour)// &
      '" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" opacity="0.10"/>'
    write(file_unit, '(a)') &
      '  <use href="#orbit" fill="none" stroke="'//trim(colour)// &
      '" stroke-width="0.9" stroke-linecap="round" stroke-linejoin="round" opacity="0.88"/>'
    write(file_unit, '(a)') '</svg>'
    close(file_unit)
  end subroutine write_svg

end program strange_attractors
